// <auto-generated />
namespace Social.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mgr_full : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mgr_full));
        
        string IMigrationMetadata.Id
        {
            get { return "201606251029254_mgr_full"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
